name: ANGLE DLLs
on:
  push:
    branches:
      - master
      - angle-or-devil

env:
  ANGLE_VERSION: 4484

jobs:
  linux-test-build:
    name: "x86/x64"
    runs-on: windows-2019
    steps:
    - name: Install Depot Tools
      run: |
        Invoke-WebRequest -Uri "https://storage.googleapis.com/chrome-infra/depot_tools.zip" -OutFile depot_tools.zip
        Expand-Archive -Path depot_tools.zip -DestinationPath depot_tools
        Remove-Item depot_tools.zip
        echo "$pwd\depot_tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Clone ANGLE
      run: |
        git clone https://github.com/google/angle.git
      env:
        DEPOT_TOOLS_WIN_TOOLCHAIN: 0

    - name: Fetch Cached third_party
      id: thirdparty-cache
      uses: actions/cache@v2
      with:
        path: angle/third_party/
        key: thirdparty-${{ env.ANGLE_VERSION }}

    - name: Build ANGLE
      run: |
        echo "$pwd\depot_tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        cd angle
        python .\scripts\bootstrap.py
        gclient sync
        git checkout chromium/${{ env.ANGLE_VERSION }}
        gn gen out/x64 --args='is_debug=false dcheck_always_on=false target_cpu=\"x64\"'
        ninja -C out/x64 libEGL libGLESv2
      env:
        DEPOT_TOOLS_WIN_TOOLCHAIN: 0
