name: ANGLE DLLs
on:
  push:
    branches:
      - master
      - angle-or-devil

env:
  ANGLE_VERSION: 4484

jobs:
  linux-test-build:
    name: "x86/x64"
    runs-on: windows-2019
    steps:
    - name: Install Depot Tools
      run: |
        Invoke-WebRequest -Uri "https://storage.googleapis.com/chrome-infra/depot_tools.zip" -OutFile depot_tools.zip
        Expand-Archive -Path depot_tools.zip -DestinationPath depot_tools
        Remove-Item depot_tools.zip
        echo "$pwd\depot_tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Clone ANGLE
      run: |
        git clone https://github.com/google/angle.git
        cd angle
        python .\scripts\bootstrap.py
      env:
        DEPOT_TOOLS_WIN_TOOLCHAIN: 0

    - name: Fetch Cached third_party
      id: 3rdparty-cache
      uses: actions/cache@v2
      with:
        path: angle/third_party/
        key: thirdparty-${{ env.ANGLE_VERSION }}

    - name: Build ANGLE
      run: |
        cd angle
        gclient sync
        git checkout chromium/${{ env.ANGLE_VERSION }}
        gn gen out/x64 --args="is_debug=false dcheck_always_on=false target_cpu=x64"
        autoninja -C out/x64 libGLESv2 libEGL
      env:
        DEPOT_TOOLS_WIN_TOOLCHAIN: 0
