name: taisei-build-test

on:
  push:
    branches:
      - master
    paths:
      - "**.c"
      - "**.h"
      - "**.yml"
      - "**.yaml"
      - "**.build"
  pull_request:
    paths:
      - "**.c"
      - "**.h"
      - "**.yml"
      - "**.yaml"
      - "**.build"

jobs:
  linux-test-build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Checkout Submodules
      run: git submodule update --init --recursive

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Meson/Ninja (Pip)
      run: pip install meson ninja

    - name: Install Build Tools (apt)
      run: sudo apt install meson build-essential libsdl2-dev libogg-dev libopusfile-dev libpng-dev libzip-dev libx11-dev libwayland-dev python3-docutils libwebp-dev

    - name: Configure - Step 1 (Meson)
      run: meson setup --wrap-mode=nofallback build/ -Db_lto=false -Dstrip=false -Ddeprecation_warnings=no-error

    - name: Configure - Step 2 (Meson)
      run: meson configure build/ -Dwerror=true

    - name: Build (Ninja)
      run: meson compile -C build/

    - name: Upload Log
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: taisei_linux_fail_log
        path: build/meson-logs/meson-log.txt

  macos-test-build:
    runs-on: macos-10.15
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Checkout Submodules
      run: git submodule update --init --recursive

    - name: Set Up Build Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Build Tools (brew)
      run: brew install gcc meson pkg-config docutils pygments freetype2 libzip opusfile libvorbis webp sdl2 ninja

    - name: Configure - Step 1 (Meson)
      run: meson setup --wrap-mode=nofallback build/ -Db_lto=false -Dstrip=false -Ddeprecation_warnings=no-error

    - name: Configure - Step 2 (Meson)
      run: meson configure build/ -Dwerror=true

    - name: Build (Ninja)
      run: meson compile -C build/

    - name: Upload Log
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: taisei_macos_fail_log
        path: build/meson-logs/meson-log.txt
