name: "Publish Taisei Binaries"

# manual run only for publishing
on:
  workflow_dispatch:
    inputs:
      draftRelease:
        description: "Is this a 'draft' release? (MUST ANSWER EITHER 'true' OR 'false' AS STRING INPUT)"
        required: true
        default: "false"
      preRelease:
        description: "Is this a 'prerelease'? (MUST ANSWER EITHER 'true' OR 'false' AS STRING INPUT)"
        required: true
        default: "false"
      tag:
        required: true
        description: "Release tag to publish. (i.e: v1.4.0)"
        default: "v1.x.x"
    tags:
      - v*.*.*
      - v*.*.*-rc
      - v*.*.*-beta

jobs:
  taisei-release:
    name: "Taisei Release Pipeline"
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: refs/tags/${{ github.event.inputs.tag }}
          recursive: true

      - name: Set Env Vars
        run: |
          echo "taisei_version=$(echo '${{ github.event.inputs.tag }}' | sed 's/^v//g')" >> $GITHUB_ENV
          echo "taisei_base_tag=$(echo '${{ env.taisei_version }}' | sed -E 's/-rc$|-beta$/g')" >> $GITHUB_ENV

      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v1
        env:
           GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
           PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Download Taisei Release Artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: release.yml
          workflow_conclusion: success
          path: /opt

      - name: Create SHA256Sums
        run: |
          sha256sum /opt/linux-x86_64-${{ env.taisei_version }}-txz/Taisei-${{ env.taisei_version }}-linux-x86_64.tar.xz > /opt/linux-x86_64-${{ env.taisei_version }}-txz/Taisei-${{ env.taisei_version }}-linux-x86_64.tar.xz.sha256
          sha256sum /opt/macos-x86_64-${{ env.taisei_version }}-dmg/Taisei-${{ env.taisei_version }}-macOS-x86_64.dmg > /opt/macos-x86_64-${{ env.taisei_version }}-dmg/Taisei-${{ env.taisei_version }}-macOS-x86_64.dmg.sha256
          sha256sum /opt/windows-x86_64-${{ env.taisei_version }}-setup-zip/Taisei-${{ env.taisei_version }}-setup-x86_64.zip > /opt/windows-x86_64-${{ env.taisei_version }}-setup-zip/Taisei-${{ env.taisei_version }}-setup-x86_64.zip.sha256
          sha256sum /opt/windows-x86_64-${{ env.taisei_version }}-setup-exe/Taisei-${{ env.taisei_version }}-setup-x86_64.exe > /opt/windows-x86_64-${{ env.taisei_version }}-setup-exe/Taisei-${{ env.taisei_version }}-setup-x86_64.exe.sha256
          sha256sum /opt/emscripten-wasm32-${{ env.taisei_version }}-txz/Taisei-${{ env.taisei_version }}-emscripten-wasm32.tar.xz > /opt/emscripten-wasm32-${{ env.taisei_version }}-txz/Taisei-${{ env.taisei_version }}-emscripten-wasm32.tar.xz.sha256
          sha256sum /opt/switch-aarch64-${{ env.taisei_version }}-zip/Taisei-${{ env.taisei_version }}-switch-aarch64.zip > /opt/switch-aarch64-${{ env.taisei_version }}-zip/Taisei-${{ env.taisei_version }}-switch-aarch64.zip.sha256sum
          sha256sum /opt/source-${{ env.taisei_version }}-txz/Taisei-${{ env.taisei_version }}-source.tar.xz > /opt/source-${{ env.taisei_version }}-txz/Taisei-${{ env.taisei_version }}-source.tar.xz
          # TODO: re-enable these when build issues are fixed
          # sha256sum /opt/windows-x86-${{ env.taisei_version }}-setup-zip/Taisei-${{ env.taisei_version }}-setup-x86.zip > /opt/windows-x86-${{ env.taisei_version }}-setup-zip/Taisei-${{ env.taisei_version }}-setup-x86.zip.sha256
          # sha256sum /opt/windows-x86-${{ env.taisei_version }}-setup-exe/Taisei-${{ env.taisei_version }}-setup-x86.exe > /opt/windows-x86-${{ env.taisei_version }}-setup-exe/Taisei-${{ env.taisei_version }}-setup-x86.exe.sha256
          # sha256sum /opt/macos-aarch64-${{ env.taisei_version }}/Taisei-${{ env.taisei_version }}-macOS-aarch64.dmg > /opt/macos-aarch64-${{ env.taisei_version }}/Taisei-${{ env.taisei_version }}-macOS-aarch64.dmg.sha256

      - name: GPG Sign Packages
        run: |
          gpg /opt/linux-x86_64-${{ env.taisei_version }}-txz/Taisei-${{ env.taisei_version }}-linux-x86_64.tar.xz.sig --detach-sig /opt/linux-x86_64-${{ env.taisei_version }}-txz/Taisei-${{ env.taisei_version }}-linux-x86_64.tar.xz
          gpg --output /opt/macos-x86_64-${{ env.taisei_version }}-dmg/Taisei-${{ env.taisei_version }}-macOS-x86_64.dmg.sig --detach-sig /opt/macos-x86_64-${{ env.taisei_version }}-dmg/Taisei-${{ env.taisei_version }}-macOS-x86_64.dmg
          gpg --output /opt/windows-x86_64-${{ env.taisei_version }}-setup-zip/Taisei-${{ env.taisei_version }}-setup-x86_64.zip.sig --detach-sig /opt/windows-x86_64-${{ env.taisei_version }}-setup-zip/Taisei-${{ env.taisei_version }}-setup-x86_64.zip
          gpg --output /opt/windows-x86_64-${{ env.taisei_version }}-setup-exe/Taisei-${{ env.taisei_version }}-setup-x86_64.exe.sig --detach-sig /opt/windows-x86_64-${{ env.taisei_version }}-setup-exe/Taisei-${{ env.taisei_version }}-setup-x86_64.exe
          gpg --output /opt/emscripten-wasm32-${{ env.taisei_version }}-txz/Taisei-${{ env.taisei_version }}-emscripten-wasm32.tar.xz.sig --detach-sig /opt/emscripten-wasm32-${{ env.taisei_version }}-txz/Taisei-${{ env.taisei_version }}-emscripten-wasm32.tar.xz
          gpg --output /opt/switch-aarch64-${{ env.taisei_version }}-zip/Taisei-${{ env.taisei_version }}-switch-aarch64.zip.sig --detach-sig /opt/switch-aarch64-${{ env.taisei_version }}-zip/Taisei-${{ env.taisei_version }}-switch-aarch64.zip.gpg
          gpg --output /opt/source-${{ env.taisei_version }}-txz/Taisei-${{ env.taisei_version }}-source.tar.xz.sig --detach-sig /opt/source-${{ env.taisei_version }}-txz/Taisei-${{ env.taisei_version }}-source.tar.xz.gpg
          # TODO: re-enable these when build issues are fixed
          # gpg --output /opt/windows-x86-${{ env.taisei_version }}-setup-zip/Taisei-${{ env.taisei_version }}-setup-x86.zip.sig --detach-sig /opt/windows-x86-${{ env.taisei_version }}-setup-zip/Taisei-${{ env.taisei_version }}-setup-x86.zip
          # gpg --output /opt/windows-x86-${{ env.taisei_version }}-setup-exe/Taisei-${{ env.taisei_version }}-setup-x86.exe.sig --detach-sig /opt/windows-x86-${{ env.taisei_version }}-setup-exe/Taisei-${{ env.taisei_version }}-setup-x86.exe
          # gpg --output /opt/macos-aarch64-${{ env.taisei_version }}/Taisei-${{ env.taisei_version }}-macOS-aarch64.dmg.sig --detach-sig /opt/macos-aarch64-${{ env.taisei_version }}/Taisei-${{ env.taisei_version }}-macOS-aarch64.dmg

      - name: Release Taisei Packages
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: ${{ github.event.inputs.draftRelease }}
          prerelease: ${{ github.event.inputs.preRelease }}
          body_path: changelogs/changelog-${{ env.taisei_base_tag }}.txt
          name: ${{ github.event.inputs.tag }}
          tag_name: ${{ github.event.inputs.tag }}
          files: |
            /opt/linux-x86_64-${{ env.taisei_version }}/Taisei-${{ env.taisei_version }}-linux-x86_64.tar.xz
            /opt/linux-x86_64-${{ env.taisei_version }}/Taisei-${{ env.taisei_version }}-linux-x86_64.tar.xz.sha256
            /opt/linux-x86_64-${{ env.taisei_version }}/Taisei-${{ env.taisei_version }}-linux-x86_64.tar.xz.sig
            /opt/macos-x86_64-${{ env.taisei_version }}/Taisei-${{ env.taisei_version }}-macOS-x86_64.dmg
            /opt/macos-x86_64-${{ env.taisei_version }}/Taisei-${{ env.taisei_version }}-macOS-x86_64.dmg.sha256sum
            /opt/macos-x86_64-${{ env.taisei_version }}/Taisei-${{ env.taisei_version }}-macOS-x86_64.dmg.sig
            /opt/windows-x86_64-${{ env.taisei_version }}-setup-exe/Taisei-${{ env.taisei_version }}-setup-x86_64.exe
            /opt/windows-x86_64-${{ env.taisei_version }}-setup-exe/Taisei-${{ env.taisei_version }}-setup-x86_64.exe.sha256
            /opt/windows-x86_64-${{ env.taisei_version }}-setup-exe/Taisei-${{ env.taisei_version }}-setup-x86_64.exe.sig
            /opt/windows-x86_64-${{ env.taisei_version }}-setup-zip/Taisei-${{ env.taisei_version }}-setup-x86_64.zip
            /opt/windows-x86_64-${{ env.taisei_version }}-setup-zip/Taisei-${{ env.taisei_version }}-setup-x86_64.zip.sha256
            /opt/windows-x86_64-${{ env.taisei_version }}-setup-zip/Taisei-${{ env.taisei_version }}-setup-x86_64.zip.sig
            /opt/emscripten-wasm32-${{ env.taisei_version }}-txz/Taisei-${{ env.taisei_version }}-emscripten-wasm32.tar.xz
            /opt/emscripten-wasm32-${{ env.taisei_version }}-txz/Taisei-${{ env.taisei_version }}-emscripten-wasm32.tar.xz.sha256
            /opt/emscripten-wasm32-${{ env.taisei_version }}-txz/Taisei-${{ env.taisei_version }}-emscripten-wasm32.tar.xz.sig
            /opt/switch-aarch64-${{ env.taisei_version }}-zip/Taisei-${{ env.taisei_version }}-switch-aarch64.zip
            /opt/switch-aarch64-${{ env.taisei_version }}-zip/Taisei-${{ env.taisei_version }}-switch-aarch64.zip.sha256sum
            /opt/switch-aarch64-${{ env.taisei_version }}-zip/Taisei-${{ env.taisei_version }}-switch-aarch64.zip.sig
            /opt/source-${{ env.taisei_version }}-txz/Taisei-${{ env.taisei_version }}-source.tar.xz
            /opt/source-${{ env.taisei_version }}-txz/Taisei-${{ env.taisei_version }}-source.tar.xz.sha256sum
            /opt/source-${{ env.taisei_version }}-txz/Taisei-${{ env.taisei_version }}-source.tar.xz.sig
            # TODO: re-enable these when build issues are fixed
            # /opt/windows-x86-${{ env.taisei_version }}-setup-exe/Taisei-${{ env.taisei_version }}-setup-x86.exe
            # /opt/windows-x86-${{ env.taisei_version }}-setup-exe/Taisei-${{ env.taisei_version }}-setup-x86.exe.sha256
            # /opt/windows-x86-${{ env.taisei_version }}-setup-exe/Taisei-${{ env.taisei_version }}-setup-x86.exe.sig
            # /opt/windows-x86-${{ env.taisei_version }}-setup-zip/Taisei-${{ env.taisei_version }}-setup-x86.zip
            # /opt/windows-x86-${{ env.taisei_version }}-setup-zip/Taisei-${{ env.taisei_version }}-setup-x86.zip.sha256
            # /opt/windows-x86-${{ env.taisei_version }}-setup-zip/Taisei-${{ env.taisei_version }}-setup-x86.zip.sig
            # /opt/macos-aarch64-${{ env.taisei_version }}/Taisei-${{ env.taisei_version }}-macOS-aarch64.dmg
            # /opt/macos-aarch64-${{ env.taisei_version }}/Taisei-${{ env.taisei_version }}-macOS-aarch64.dmg.sha256
            # /opt/macos-aarch64-${{ env.taisei_version }}/Taisei-${{ env.taisei_version }}-macOS-aarch64.dmg.sig

      # TODO: needs DEPLOY_KEY
      # - name: Deploy to GitHub Pages (Stable)
      #   uses: JamesIves/github-pages-deploy-action@4.1.1
      #   with:
      #     branch: live
      #     target-folder: ./play/stable/
      #     folder: ./build-weekly/
      #     repository-name: taisei-project/taisei-website-new
      #     commit-message: "${{ github.repository }}@${{ github.sha }}"
      #     ssh-key: ${{ secrets.DEPLOY_KEY }}
