name: Taisei Release Build
on:
  push:
    branches:
      - rc/v*.*.*
      - testing/v*.*.*
    tags:
      - v*.*.*
      - testing/v*.*.*
      - rc/v*.*.*

env:
  EM_VERSION: '2.0.19'
  EM_CACHE_FOLDER: 'emsdk'
  TAISEI_NOPRELOAD: 0
  TAISEI_PRELOAD_REQUIRED: 1

jobs:
  linux-release:
    name: Linux Release Build (x64)
    runs-on: ubuntu-18.04
    steps:
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Build Tools (apt)
      run: >
        sudo apt update

        sudo apt install -y -qq
        build-essential
        libsdl2-dev
        libx11-dev
        libwayland-dev
        python3-docutils

        pip install
        meson==0.56.2
        ninja
        zstandard

    # - name: Set Build Tag
    #   if: ${{ startsWith(github.ref, 'refs/tags/') }}
    #   run: echo "Hi!"

    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set Tag Output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}

    - name: Configure (Meson)
      run: >
        meson setup build/linux
        --prefix=$(pwd)/build-release
        --native-file misc/ci/linux-x86_64-build-release.ini

    - name: Build & Install
      run: |
        meson compile -C build/linux --verbose
        meson install -C build/linux

    - name: Run Test (Taisei)
      run: $(pwd)/build-release/bin/taisei -R $(pwd)/misc/ci/tests/test-replay.tsr
      env:
        TAISEI_NOPRELOAD: ${{ env.TAISEI_NOPRELOAD }}
        TAISEI_PRELOAD_REQUIRED: ${{ env.TAISEI_PRELOAD_REQUIRED }}

    - name: Build Package
      run: meson compile txz -C build/linux --verbose

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: linux-x86_64-${{ steps.vars.outputs.tag }}
        path: build/linux/Taisei-${{ steps.vars.outputs.tag }}-linux-x86_64.tar.xz
        if-no-files-found: error

    - name: Upload Log
      uses: actions/upload-artifact@v2
      with:
        name: taisei_linux_release_log
        path: build/linux/meson-logs/meson-log.txt
        if-no-files-found: warn

  macos-release-intel:
    name: macOS Release (Intel)
    runs-on: macos-10.15
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: "recursive"

    - name: Set Up Build Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Build Tools
      run: >
        brew install
        gcc
        pkg-config
        docutils
        pygments
        create-dmg

        pip install
        meson==0.56.2
        ninja
        zstandard

    - name: Set Build Tag
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}

    - name: Configure (Meson)
      run: >
        meson setup build/macos
        --prefix=$(pwd)/build-release
        --native-file misc/ci/macos-x86_64-build-release.ini

    - name: Build & Install
      run: |
        meson compile -C build/macos --verbose
        meson install -C build/macos

    - name: Run Test (Taisei)
      run: $(pwd)/build-release/Taisei.app/Contents/MacOS/Taisei -R $(pwd)/misc/ci/tests/test-replay.tsr
      env:
        TAISEI_NOPRELOAD: ${{ env.TAISEI_NOPRELOAD }}
        TAISEI_PRELOAD_REQUIRED: ${{ env.TAISEI_PRELOAD_REQUIRED }}

    - name: Build Package
      run: meson compile dmg -C build/macos --verbose

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: macos-x86_64-${{ steps.vars.outputs.tag }}
        path: build/macos/Taisei-${{ steps.vars.outputs.tag }}-macOS-x86_64.dmg
        if-no-files-found: error

    - name: Upload Log
      uses: actions/upload-artifact@v2
      with:
        name: taisei_macos_intel_release_log
        path: build/macos/meson-logs/meson-log.txt
        if-no-files-found: warn

  macos-release-arm64:
    name: macOS Release (Apple Silicon)
    runs-on: macos-11.0
    # making this message-dependent until GitHub actually releases macOS 11.0 runners
    # mandatory for aarch64 builds, unfortunately
    # see: https://github.com/actions/virtual-environments/issues/2486
    if: "contains(github.event.head_commit.message, 'run macos aarch64 build')"
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: "recursive"

    - name: Set Up Build Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Build Tools
      run: >
        brew install
        gcc
        pkg-config
        docutils
        pygments
        create-dmg

        pip install
        meson==0.56.2
        ninja
        zstandard

    - name: Set Build Tag
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}

    - name: Configure (Meson)
      run: >
        meson setup build/macos
        --prefix=$(pwd)/build-release
        --cross-file misc/ci/macos-aarch64-build-release.ini

    - name: Build & Install
      run: |
        meson compile -C build/macos --verbose
        meson install -C build/macos

    - name: Build Package
      run: meson compile dmg -C build/macos --verbose

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: macos-aarch64-${{ steps.vars.outputs.tag }}
        path: build/macos/Taisei-${{ steps.vars.outputs.tag }}-macOS-aarch64.dmg
        if-no-files-found: error

    - name: Upload Log
      uses: actions/upload-artifact@v2
      with:
        name: taisei_macos_arm64_release_log
        path: build/macos/meson-logs/meson-log.txt
        if-no-files-found: warn

  windows-release-x64:
    name: Windows Release (x64)
    runs-on: ubuntu-20.04
    container: mstorsjo/llvm-mingw:20210423 # cross-compiler with mingw
    steps:
    - name: Install Tools
      run: >
        apt update

        apt install -y -qq software-properties-common

        add-apt-repository ppa:git-core/ppa -y

        apt install -y -qq
        python3-docutils
        python3-pip
        git
        wget
        nsis

        pip3 install
        meson==0.56.2
        ninja
        zstandard

    # install 3.x on top of older Ubuntu
    # 3.x is only available for 20.04+, so --force-all the install (it still works but complains about libc versions)
    - name: Install NSIS 3.x
      run: >
        wget http://security.ubuntu.com/ubuntu/pool/universe/n/nsis/nsis-pluginapi_3.05-2_all.deb -P /tmp

        wget http://security.ubuntu.com/ubuntu/pool/universe/n/nsis/nsis-common_3.05-2_all.deb -P /tmp

        wget http://security.ubuntu.com/ubuntu/pool/universe/n/nsis/nsis_3.05-2_amd64.deb -P /tmp

        dpkg -i --force-all
        /tmp/nsis-common_3.05-2_all.deb
        /tmp/nsis_3.05-2_amd64.deb
        /tmp/nsis-pluginapi_3.05-2_all.deb

    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: "recursive"

    - name: Checkout ANGLE DLLs (x64)
      uses: actions/checkout@v2
      with:
        repository: taisei-project/angle-compiled
        path: angle-compiled

    - name: Set Env Vars
      id: vars
      run: |
        echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}
        tee misc/ci/windows-x64-ephemeral-release-ci.ini <<EOF >/dev/null
        [constants]
        libgles_path = '$(pwd)/angle-compiled/dll/x64/libGLESv2.dll'
        libegl_path = '$(pwd)/angle-compiled/dll/x64/libEGL.dll'
        EOF

    - name: Configure Taisei (Meson)
      run: >
        meson setup build/windows
        --prefix=$(pwd)/build-release
        --cross-file misc/ci/windows-llvm_mingw-x86_64-build-release.ini
        --cross-file misc/ci/windows-x64-ephemeral-release-ci.ini

    - name: Build (Package EXE x64)
      run: meson compile nsis -C build/windows --verbose

    - name: Upload Artifacts (EXE x64)
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: windows-x86_64-${{ steps.vars.outputs.tag }}-setup-exe
        path: build/windows/Taisei-${{ steps.vars.outputs.tag }}-setup-x86_64.exe
        if-no-files-found: error

    - name: Build (Package ZIP x64)
      run: ninja zip -C build/windows --verbose

    - name: Upload Artifact (ZIP x64)
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: windows-x86_64-${{ steps.vars.outputs.tag }}-zip
        path: build/windows/Taisei-${{ steps.vars.outputs.tag }}-windows-x86_64.zip
        if-no-files-found: error

    - name: Upload Log
      uses: actions/upload-artifact@v2
      with:
        name: taisei_windows_x64_release_log
        path: build/windows/meson-logs/meson-log.txt
        if-no-files-found: warn

  windows-release-x86:
    name: Windows Release (x86)
    runs-on: ubuntu-20.04
    container: mstorsjo/llvm-mingw:20210423 # cross-compiler with mingw
    steps:
    - name: Install tools (Apt)
      run: >
        apt update

        apt install -y -qq software-properties-common

        add-apt-repository ppa:git-core/ppa -y

        apt install -y -qq
        python3-docutils
        python3-pip
        git
        wget
        nsis

        pip3 install
        meson==0.56.2
        ninja
        zstandard

    # install 3.x on top of older Ubuntu
    # 3.x is only available for 20.04+, so --force-all the install (it still works but complains about libc versions)
    - name: Install NSIS 3.x
      run: >
        wget http://security.ubuntu.com/ubuntu/pool/universe/n/nsis/nsis-pluginapi_3.05-2_all.deb -P /tmp

        wget http://security.ubuntu.com/ubuntu/pool/universe/n/nsis/nsis-common_3.05-2_all.deb -P /tmp

        wget http://security.ubuntu.com/ubuntu/pool/universe/n/nsis/nsis_3.05-2_amd64.deb -P /tmp

        dpkg -i --force-all
        /tmp/nsis-common_3.05-2_all.deb
        /tmp/nsis_3.05-2_amd64.deb
        /tmp/nsis-pluginapi_3.05-2_all.deb

    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: "recursive"

    - name: Checkout ANGLE DLLs (x86)
      uses: actions/checkout@v2
      with:
        repository: taisei-project/angle-compiled
        path: angle-compiled

    - name: Set Build Vars
      id: vars
      run: |
        echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}
        tee misc/ci/windows-x86-ephemeral-release-ci.ini <<EOF >/dev/null
        [constants]
        libgles_path = '$(pwd)/angle-compiled/dll/x86/libGLESv2.dll'
        libegl_path = '$(pwd)/angle-compiled/dll/x86/libEGL.dll'
        EOF

    - name: Configure Taisei (Meson)
      run: >
        meson setup build/windows
        --prefix=$(pwd)/build-release
        --cross-file misc/ci/windows-llvm_mingw-x86-build-release.ini
        --cross-file misc/ci/windows-x86-ephemeral-release-ci.ini

    - name: Build (Package EXE x86)
      run: meson compile nsis -C build/windows --verbose

    - name: Upload Artifacts (EXE x86)
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: windows-x86-${{ steps.vars.outputs.tag }}-setup-exe
        path: build/windows/Taisei-${{ steps.vars.outputs.tag }}-setup-x86.exe
        if-no-files-found: error

    - name: Build (Package ZIP x86)
      run: ninja zip -C build/windows --verbose

    - name: Upload Artifact (ZIP x86)
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: windows-x86-${{ steps.vars.outputs.tag }}-zip
        path: build/windows/Taisei-${{ steps.vars.outputs.tag }}-windows-x86.zip
        if-no-files-found: error

    - name: Upload Log
      uses: actions/upload-artifact@v2
      with:
        name: taisei_windows_x86_release_log
        path: build/windows/meson-logs/meson-log.txt
        if-no-files-found: warn

  emscripten-test-build:
    name: Emscripten Release (WebGL)
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set Up Build Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Build Tools
      run: >
        sudo apt update || true

        sudo apt install -y -qq
        python3-docutils
        python3-pip
        git

        pip install
        meson==0.56.2
        ninja
        zstandard

    - name: Pull cached emsdk
      id: cache-emsdk
      uses: actions/cache@v2
      with:
        path: ${{ env.EM_CACHE_FOLDER }}
        key: ${{ env.EM_VERSION }}-${{ runner.os }}

    - name: Install emsdk
      if: steps.cache-emsdk.outputs.cache-hit != 'true'
      run: |
        rm -rf emsdk/
        git clone https://github.com/emscripten-core/emsdk.git
        emsdk/emsdk install ${{ env.EM_VERSION }}
        emsdk/emsdk activate ${{ env.EM_VERSION }}

    - name: Verify emsdk
      run: |
        source emsdk/emsdk_env.sh
        emcc -v
        tee misc/ci/emscripten-ephemeral-ci.ini <<EOF >/dev/null
        [constants]
        toolchain = '$(pwd)/emsdk/upstream/emscripten/'
        EOF

    - name: Configure (Meson)
      run: >
        source emsdk/emsdk_env.sh

        meson setup build/emscripten
        --cross-file misc/ci/emscripten-ephemeral-ci.ini
        --cross-file misc/ci/emscripten-build-test-ci.ini
        --prefix=$(pwd)/build-test

        meson configure
        -Dbuild.cpp_std=gnu++14
        build/emscripten

    - name: Build
      run: |
        source emsdk/emsdk_env.sh
        # run twice due to a header race condition with SPIRV-Tools
        meson compile txz -C build/emscripten --verbose || true
        meson compile txz -C build/emscripten --verbose

    - name: Upload Artifact (WebGL WASM32)
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: emscripten-wasm32-${{ steps.vars.outputs.tag }}-txz
        path: build/emscripten/Taisei-${{ steps.vars.outputs.tag }}-emscripten-wasm32.tar.xz
        if-no-files-found: error

    - name: Upload Log
      uses: actions/upload-artifact@v2
      with:
        name: taisei_emscripten_build_log
        path: build/meson-logs/meson-log.txt
        if-no-files-found: warn
